name: Publish
on:
  workflow_call:
env:
  FULL_PACKAGE_VERSION: ${{ format('0.1.{0}+{1}', github.run_number, github.sha) }}
  PACKAGE_VERSION: ${{ format('0.1.{0}', github.run_number) }}
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pack
        run: dotnet pack src/core/decaf/decaf.csproj -c Release -p:Version=${FULL_PACKAGE_VERSION} -o ./output
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: package
          path: ./output
          retention-days: 0

  publish:
    runs-on: ubuntu-latest
    needs: [pack]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: package
        path: ./output
    - name: Upload to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_NAME: ${{ format('decaf-orm.{0}.nupkg', env.PACKAGE_VERSION) }}
      run: |
        dotnet nuget push ./output/${PACKAGE_NAME} \
          -k ${NUGET_API_KEY} \
          -s https://api.nuget.org/v3/index.json
    - name: Persist Version
      env:
        GH_TOKEN: ${{ secrets.GH_CLI_PAT }}
      run: |
       gh variable set LATEST_DECAF --body=${PACKAGE_VERSION} -R daniel-buchanan/decaf-orm